defaults: &defaults
  working_directory: /go/src/github.com/chris-ramon/graphql
  steps:
    - checkout
    - run: go get -v -t -d ./...
    - run: go test ./...
 
version: 2
jobs:
  golang:1.8.7:
    <<: *defaults
    docker:
      - image: circleci/golang:1.8.7
  golang:1.9.7:
    <<: *defaults
    docker:
      - image: circleci/golang:1.9.7
  golang:latest:
    <<: *defaults
    docker:
      - image: circleci/golang:latest
  codecov:
    working_directory: /go/src/github.com/chris-ramon/graphql
    docker:
      - image: circleci/golang:latest
    steps:
      - checkout
      - run: go get -v -t -d ./...
      - run: go test -race -coverprofile=coverage.txt -covermode=atomic
      - run: bash <(curl -s https://codecov.io/bash)

workflows:
  version: 2
  build:
    jobs:
      - golang:1.8.7
      - golang:1.9.7
      - golang:latest
      - codecov
