version: 2
jobs:
  golang:1-8-7:
    docker:
      - image: circleci/golang:1.8.7
    working_directory: /go/src/github.com/chris-ramon/graphql
    steps:
      - checkout
      - run: go get -v -t -d ./...
      - run: go test ./...
  golang:1.9.7:
    docker:
      - image: circleci/golang:1.9.7
    working_directory: /go/src/github.com/chris-ramon/graphql
    steps:
      - checkout
      - run: go get -v -t -d ./...
      - run: go test ./...
  golang:latest:
    docker:
      - image: circleci/golang:latest
    working_directory: /go/src/github.com/chris-ramon/graphql
    steps:
      - checkout
      - run: go get -v -t -d ./...
      - run: go test ./...

workflows:
  version: 2
  build:
    jobs:
      - golang:1.8.7
      - golang:1.9.7
      - golang:latest
