version: 2
jobs:
  build-go1-8-7:
    docker:
      - image: circleci/golang:1.8.7
    working_directory: /go/src/github.com/chris-ramon/graphql
    steps:
      - checkout
      - run: go get -v -t -d ./...
      - run: go test ./...
  build-go1-9-7:
    docker:
      - image: circleci/golang:1.9.7
    working_directory: /go/src/github.com/chris-ramon/graphql
    steps:
      - checkout
      - run: go get -v -t -d ./...
      - run: go test ./...

workflows:
	version: 2
	build:
		jobs:
			- build-go1-8-7
			- build-go1-9-7
